
/**
 * Segunda parte do mapeamento de exercícios para URLs de imagens específicas
 * Separando em dois arquivos para melhor manutenção
 */

import { SUPABASE_PUBLIC_URL } from './constants';

// Segunda parte - Mapeamento de imagens
export const exerciseImageMapPart2: Record<string, string> = {
  "Jump lunge": `${SUPABASE_PUBLIC_URL}/images/Jump%20lunge.png`,
  "Jump squat": `${SUPABASE_PUBLIC_URL}/images/Jump%20squat.png`,
  "Jumping jacks": `${SUPABASE_PUBLIC_URL}/images/Jumping%20jacks.png`,
  "Leg press 45°": `${SUPABASE_PUBLIC_URL}/images/Leg_press_45.png`,
  "L-sit": `${SUPABASE_PUBLIC_URL}/images/L-sit.png`,
  "Marcha estacionária": `${SUPABASE_PUBLIC_URL}/images/Marcha_estacionaria.png`,
  "Mergulho em barras": `${SUPABASE_PUBLIC_URL}/images/Mergulho%20em%20barras.png`,
  "Mobilidade articular": `${SUPABASE_PUBLIC_URL}/images/Mobilidade%20articular.png`,
  "Muscle-up": `${SUPABASE_PUBLIC_URL}/images/Muscle-up.png`,
  "Panturrilha em pé": `${SUPABASE_PUBLIC_URL}/images/Panturrilha_em_pe.png`,
  "Pike push-up (flexão elevada)": `${SUPABASE_PUBLIC_URL}/images/Pike_push_up.png`,
  "Pistol squat": `${SUPABASE_PUBLIC_URL}/images/Pistol%20squat.png`,
  "Pistol squat assistido": `${SUPABASE_PUBLIC_URL}/images/Pistol%20squat%20assistido.png`,
  "Prancha": `${SUPABASE_PUBLIC_URL}/images/Prancha.png`,
  "Prancha com drag": `${SUPABASE_PUBLIC_URL}/images/Prancha%20com%20drag.png`,
  "Prancha com shoulder tap": `${SUPABASE_PUBLIC_URL}/images/Prancha%20com%20shoulder%20tap.png`,
  "Prancha frontal": `${SUPABASE_PUBLIC_URL}/images/Prancha_frontal.png`,
  "Prancha lateral": `${SUPABASE_PUBLIC_URL}/images/Prancha%20lateral.png`,
  "Prancha no joelho": `${SUPABASE_PUBLIC_URL}/images/Prancha_no_joelho.png`,
  "Pseudo planche push-up": `${SUPABASE_PUBLIC_URL}/images/Pseudo%20planche%20push-up.png`,
  "Pull-up": `${SUPABASE_PUBLIC_URL}/images/Pull-up.png`,
  "Pull-up (barra fixa)": `${SUPABASE_PUBLIC_URL}/images/Pull-up_barra_fixa.png`,
  "Pull-up negativa": `${SUPABASE_PUBLIC_URL}/images/Pull-up%20negativa.png`,
  "Push-up plus": `${SUPABASE_PUBLIC_URL}/images/Push-up%20plus.png`,
  "Puxada aberta": `${SUPABASE_PUBLIC_URL}/images/Puxada_aberta.png`,
  "Puxada alta": `${SUPABASE_PUBLIC_URL}/images/Puxada_alta.png`,
  "Puxada frontal": `${SUPABASE_PUBLIC_URL}/images/Puxada_frontal.png`,
  "Remada baixa": `${SUPABASE_PUBLIC_URL}/images/Remada_baixa.png`,
  "Remada cavalinho": `${SUPABASE_PUBLIC_URL}/images/Remada_cavalinho.png`,
  "Remada curvada": `${SUPABASE_PUBLIC_URL}/images/Remada_curvada.png`,
  "Remada invertida": `${SUPABASE_PUBLIC_URL}/images/Remada%20invertida.png`,
  "Remada sentada": `${SUPABASE_PUBLIC_URL}/images/Remada_sentada.png`,
  "Remada unilateral com haltere": `${SUPABASE_PUBLIC_URL}/images/Remada_unilateral_com_haltere.png`,
  "Rosca alternada com halteres": `${SUPABASE_PUBLIC_URL}/images/Rosca_alternada_com_halteres.png`,
  "Rosca direta": `${SUPABASE_PUBLIC_URL}/images/Rosca%20direta.png`,
  "Rosca direta com barra": `${SUPABASE_PUBLIC_URL}/images/Rosca_direta_com_barra.png`,
  "Rosca scott": `${SUPABASE_PUBLIC_URL}/images/Rosca_scott.png`,
  "Rotação de tronco": `${SUPABASE_PUBLIC_URL}/images/Rotacao_de_tronco.png`,
  "Russian twist": `${SUPABASE_PUBLIC_URL}/images/Russian_twist.png`,
  "Salto em caixa ou banco": `${SUPABASE_PUBLIC_URL}/images/Salto%20em%20caixa%20ou%20banco.png`,
  "Sprint e caminhada": `${SUPABASE_PUBLIC_URL}/images/Sprint%20e%20caminhada.png`,
  "Sprints": `${SUPABASE_PUBLIC_URL}/images/Sprints.png`,
  "Stiff": `${SUPABASE_PUBLIC_URL}/images/Stiff.png`,
  "Superman": `${SUPABASE_PUBLIC_URL}/images/Superman.png`,
  "Supino inclinado com halteres": `${SUPABASE_PUBLIC_URL}/images/Supino_inclinado_com_halteres.png`,
  "Supino máquina": `${SUPABASE_PUBLIC_URL}/images/Supino_maquina.png`,
  "Supino reto": `${SUPABASE_PUBLIC_URL}/images/Supino%20reto.png`,
  "Supino reto com barra": `${SUPABASE_PUBLIC_URL}/images/Supino_reto_com_barra.png`,
  "Supino sentado": `${SUPABASE_PUBLIC_URL}/images/Supino_sentado.png`,
  "Treino em circuito": `${SUPABASE_PUBLIC_URL}/images/Treino%20em%20circuito.png`,
  "Treino intervalado": `${SUPABASE_PUBLIC_URL}/images/Treino%20intervalado.png`,
  "Tríceps corda": `${SUPABASE_PUBLIC_URL}/images/Triceps_corda.png`,
  "Tríceps francês": `${SUPABASE_PUBLIC_URL}/images/Triceps_frances.png`,
};

