
/**
 * Mapeamento de exercícios para URLs de imagens específicas
 * Este arquivo centraliza apenas as associações entre exercícios e suas imagens
 */

import { SUPABASE_PUBLIC_URL } from './constants';

// Mapeamento de nomes de exercícios para URLs de imagens
export const exerciseImageMap: Record<string, string> = {
  // Primeira parte - Mapeamento de imagens 
  "Abdominal bicicleta": `${SUPABASE_PUBLIC_URL}/images/Abdominal_bicicleta%20(1).png`,
  "Abdominal completo": `${SUPABASE_PUBLIC_URL}/images/Abdominal_completo.png`,
  "Abdominal curto": `${SUPABASE_PUBLIC_URL}/images/Abdominal_curto.png`,
  "Abdominal infra": `${SUPABASE_PUBLIC_URL}/images/Abdominal_infra.png`,
  "Abdominal máquina": `${SUPABASE_PUBLIC_URL}/images/Abdominal_maquina.png`,
  "Abdução de quadril": `${SUPABASE_PUBLIC_URL}/images/Abducao_de_quadril.png`,
  "Afundo": `${SUPABASE_PUBLIC_URL}/images/Afundo.png`,
  "Afundo andando": `${SUPABASE_PUBLIC_URL}/images/Afundo_andando.png`,
  "Afundo búlgaro": `${SUPABASE_PUBLIC_URL}/images/Afundo_bulgaro.png`,
  "Afundo com salto": `${SUPABASE_PUBLIC_URL}/images/Afundo_com_salto.png`,
  "Afundo estático": `${SUPABASE_PUBLIC_URL}/images/Afundo_estatico.png`,
  "Agachamento búlgaro": `${SUPABASE_PUBLIC_URL}/images/Agachamento_bulgaro.png`,
  "Agachamento com salto": `${SUPABASE_PUBLIC_URL}/images/Agachamento_com_salto.png`,
  "Agachamento livre": `${SUPABASE_PUBLIC_URL}/images/Agachamento_livre.png`,
  "Agachamento na parede": `${SUPABASE_PUBLIC_URL}/images/Agachamento_na_parede.png`,
  "Agachamento Smith": `${SUPABASE_PUBLIC_URL}/images/Agachamento_Smith.png`,
  "Agachamento sumô": `${SUPABASE_PUBLIC_URL}/images/Agachamento_sumo.png`,
  "Alongamento de isquiotibiais": `${SUPABASE_PUBLIC_URL}/images/Alongamento_de_isquiotibiais.png`,
  "Alongamento de ombros": `${SUPABASE_PUBLIC_URL}/images/Alongamento_de_ombros.png`,
  "Alongamento dinâmico": `${SUPABASE_PUBLIC_URL}/images/Alongamento_dinamico.png`,
  "Alongamento final": `${SUPABASE_PUBLIC_URL}/images/Alongamento_final.png`,
  "Alongamento passivo": `${SUPABASE_PUBLIC_URL}/images/Alongamento%20passivo.png`,
  "Australian pull-up": `${SUPABASE_PUBLIC_URL}/images/Australian%20pull-up.png`,
  "Bicicleta ergométrica": `${SUPABASE_PUBLIC_URL}/images/Bicicleta_ergometrica.png`,
  "Burpee": `${SUPABASE_PUBLIC_URL}/images/Burpee.png`,
  "Cadeira extensora": `${SUPABASE_PUBLIC_URL}/images/Cadeira_extensora.png`,
  "Cadeira flexora": `${SUPABASE_PUBLIC_URL}/images/Cadeira_flexora.png`,
  "Caminhada": `${SUPABASE_PUBLIC_URL}/images/Caminhada.png`,
  "Caminhada em terreno inclinado": `${SUPABASE_PUBLIC_URL}/images/Caminhada%20em%20terreno%20inclinado.png`,
  "Caminhada no lugar": `${SUPABASE_PUBLIC_URL}/images/Caminhada%20no%20lugar.png`,
  "Cardio leve": `${SUPABASE_PUBLIC_URL}/images/Cardio%20leve.png`,
  "Cardio misto": `${SUPABASE_PUBLIC_URL}/images/Cardio%20misto.png`,
  "Cardio moderado": `${SUPABASE_PUBLIC_URL}/images/Cardio%20moderado.png`,
  "Corrida em ladeira": `${SUPABASE_PUBLIC_URL}/images/Corrida%20em%20ladeira.png`,
  "Corrida leve": `${SUPABASE_PUBLIC_URL}/images/Corrida%20leve.png`,
  "Crucifixo": `${SUPABASE_PUBLIC_URL}/images/Crucifixo.png`,
  "Crucifixo máquina": `${SUPABASE_PUBLIC_URL}/images/Crucifixo.png`,
  "Crucifixo na máquina": `${SUPABASE_PUBLIC_URL}/images/Crucifixo_maquina.png`,
  "Crunch abdominal": `${SUPABASE_PUBLIC_URL}/images/Crunch_abdominal.png`,
  "Desenvolvimento com halteres": `${SUPABASE_PUBLIC_URL}/images/Desenvolvimento_com_halteres.png`,
  "Desenvolvimento máquina": `${SUPABASE_PUBLIC_URL}/images/Desenvolvimento_maquina.png`,
  "Dips em cadeira": `${SUPABASE_PUBLIC_URL}/images/Dips%20em%20cadeira.png`,
  "Dragon flag": `${SUPABASE_PUBLIC_URL}/images/Dragon%20flag.png`,
  "Elevação de pernas": `${SUPABASE_PUBLIC_URL}/images/Elevacao_de_pernas.png`,
  "Elevação frontal": `${SUPABASE_PUBLIC_URL}/images/Elevacao_frontal.png`,
  "Elevação lateral": `${SUPABASE_PUBLIC_URL}/images/Elevacao_lateral.png`,
  "Elevação pélvica": `${SUPABASE_PUBLIC_URL}/images/Elevacao_pelvica.png`,
  "Elíptico": `${SUPABASE_PUBLIC_URL}/images/Eliptico.png`,
  "Escalador": `${SUPABASE_PUBLIC_URL}/images/Escalador.png`,
  "Esteira": `${SUPABASE_PUBLIC_URL}/images/Esteira.png`,
  "Face pull": `${SUPABASE_PUBLIC_URL}/images/Face_pull.png`,
  "Flexão de braço": `${SUPABASE_PUBLIC_URL}/images/Flexao_de_braco.png`,
  "Flexão declinada": `${SUPABASE_PUBLIC_URL}/images/Flexao_declinada.png`,
  "Flexão na parede": `${SUPABASE_PUBLIC_URL}/images/Flexao_na_parede.png`,
  "Gato-vaca": `${SUPABASE_PUBLIC_URL}/images/Gato-vaca.png`,
  "Handstand push-up na parede": `${SUPABASE_PUBLIC_URL}/images/Handstand%20push-up%20na%20parede.png`,
  "HIIT": `${SUPABASE_PUBLIC_URL}/images/HIIT.png`,
  "Hollow hold": `${SUPABASE_PUBLIC_URL}/images/Hollow%20hold.png`
};
