
/**
 * Mapeamento de exercícios para URLs de imagens e vídeos específicos
 * Este arquivo centraliza as associações entre exercícios, suas imagens e vídeos correspondentes
 */

// Base URL para imagens e vídeos no Supabase
const SUPABASE_PUBLIC_URL = "https://ipzrgpmsmasuzlaomuxj.supabase.co/storage/v1/object/public";

// Mapeamento de nomes de exercícios para URLs de imagens
export const exerciseImageMap: Record<string, string> = {
  // Primeira parte - Mapeamento de imagens 
  "Abdominal bicicleta": `${SUPABASE_PUBLIC_URL}/images/Abdominal_bicicleta%20(1).png`,
  "Abdominal completo": `${SUPABASE_PUBLIC_URL}/images/Abdominal_completo.png`,
  "Abdominal curto": `${SUPABASE_PUBLIC_URL}/images/Abdominal_curto.png`,
  "Abdominal infra": `${SUPABASE_PUBLIC_URL}/images/Abdominal_infra.png`,
  "Abdominal máquina": `${SUPABASE_PUBLIC_URL}/images/Abdominal_maquina.png`,
  "Abdução de quadril": `${SUPABASE_PUBLIC_URL}/images/Abducao_de_quadril.png`,
  "Afundo": `${SUPABASE_PUBLIC_URL}/images/Afundo.png`,
  "Afundo andando": `${SUPABASE_PUBLIC_URL}/images/Afundo_andando.png`,
  "Afundo búlgaro": `${SUPABASE_PUBLIC_URL}/images/Afundo_bulgaro.png`,
  "Afundo com salto": `${SUPABASE_PUBLIC_URL}/images/Afundo_com_salto.png`,
  "Afundo estático": `${SUPABASE_PUBLIC_URL}/images/Afundo_estatico.png`,
  "Agachamento búlgaro": `${SUPABASE_PUBLIC_URL}/images/Agachamento_bulgaro.png`,
  "Agachamento com salto": `${SUPABASE_PUBLIC_URL}/images/Agachamento_com_salto.png`,
  "Agachamento livre": `${SUPABASE_PUBLIC_URL}/images/Agachamento_livre.png`,
  "Agachamento na parede": `${SUPABASE_PUBLIC_URL}/images/Agachamento_na_parede.png`,
  "Agachamento Smith": `${SUPABASE_PUBLIC_URL}/images/Agachamento_Smith.png`,
  "Agachamento sumô": `${SUPABASE_PUBLIC_URL}/images/Agachamento_sumo.png`,
  "Alongamento de isquiotibiais": `${SUPABASE_PUBLIC_URL}/images/Alongamento_de_isquiotibiais.png`,
  "Alongamento de ombros": `${SUPABASE_PUBLIC_URL}/images/Alongamento_de_ombros.png`,
  "Alongamento dinâmico": `${SUPABASE_PUBLIC_URL}/images/Alongamento_dinamico.png`,
  "Alongamento final": `${SUPABASE_PUBLIC_URL}/images/Alongamento_final.png`,
  "Alongamento passivo": `${SUPABASE_PUBLIC_URL}/images/Alongamento%20passivo.png`,
  "Australian pull-up": `${SUPABASE_PUBLIC_URL}/images/Australian%20pull-up.png`,
  "Bicicleta ergométrica": `${SUPABASE_PUBLIC_URL}/images/Bicicleta_ergometrica.png`,
  "Burpee": `${SUPABASE_PUBLIC_URL}/images/Burpee.png`,
  "Cadeira extensora": `${SUPABASE_PUBLIC_URL}/images/Cadeira_extensora.png`,
  "Cadeira flexora": `${SUPABASE_PUBLIC_URL}/images/Cadeira_flexora.png`,
  "Caminhada": `${SUPABASE_PUBLIC_URL}/images/Caminhada.png`,
  "Caminhada em terreno inclinado": `${SUPABASE_PUBLIC_URL}/images/Caminhada%20em%20terreno%20inclinado.png`,
  "Caminhada no lugar": `${SUPABASE_PUBLIC_URL}/images/Caminhada%20no%20lugar.png`,
  "Cardio leve": `${SUPABASE_PUBLIC_URL}/images/Cardio%20leve.png`,
  "Cardio misto": `${SUPABASE_PUBLIC_URL}/images/Cardio%20misto.png`,
  "Cardio moderado": `${SUPABASE_PUBLIC_URL}/images/Cardio%20moderado.png`,
  "Corrida em ladeira": `${SUPABASE_PUBLIC_URL}/images/Corrida%20em%20ladeira.png`,
  "Corrida leve": `${SUPABASE_PUBLIC_URL}/images/Corrida%20leve.png`,
  "Crucifixo": `${SUPABASE_PUBLIC_URL}/images/Crucifixo.png`,
  "Crucifixo máquina": `${SUPABASE_PUBLIC_URL}/images/Crucifixo.png`,
  "Crucifixo na máquina": `${SUPABASE_PUBLIC_URL}/images/Crucifixo_maquina.png`,
  "Crunch abdominal": `${SUPABASE_PUBLIC_URL}/images/Crunch_abdominal.png`,
  "Desenvolvimento com halteres": `${SUPABASE_PUBLIC_URL}/images/Desenvolvimento_com_halteres.png`,
  "Desenvolvimento máquina": `${SUPABASE_PUBLIC_URL}/images/Desenvolvimento_maquina.png`,
  "Dips em cadeira": `${SUPABASE_PUBLIC_URL}/images/Dips%20em%20cadeira.png`,
  "Dragon flag": `${SUPABASE_PUBLIC_URL}/images/Dragon%20flag.png`,
  "Elevação de pernas": `${SUPABASE_PUBLIC_URL}/images/Elevacao_de_pernas.png`,
  "Elevação frontal": `${SUPABASE_PUBLIC_URL}/images/Elevacao_frontal.png`,
  "Elevação lateral": `${SUPABASE_PUBLIC_URL}/images/Elevacao_lateral.png`,
  "Elevação pélvica": `${SUPABASE_PUBLIC_URL}/images/Elevacao_pelvica.png`,
  "Elíptico": `${SUPABASE_PUBLIC_URL}/images/Eliptico.png`,
  "Escalador": `${SUPABASE_PUBLIC_URL}/images/Escalador.png`,
  "Esteira": `${SUPABASE_PUBLIC_URL}/images/Esteira.png`,
  "Face pull": `${SUPABASE_PUBLIC_URL}/images/Face_pull.png`,
  "Flexão de braço": `${SUPABASE_PUBLIC_URL}/images/Flexao_de_braco.png`,
  "Flexão declinada": `${SUPABASE_PUBLIC_URL}/images/Flexao_declinada.png`,
  "Flexão na parede": `${SUPABASE_PUBLIC_URL}/images/Flexao_na_parede.png`,
  "Gato-vaca": `${SUPABASE_PUBLIC_URL}/images/Gato-vaca.png`,
  "Handstand push-up na parede": `${SUPABASE_PUBLIC_URL}/images/Handstand%20push-up%20na%20parede.png`,
  "HIIT": `${SUPABASE_PUBLIC_URL}/images/HIIT.png`,
  "Hollow hold": `${SUPABASE_PUBLIC_URL}/images/Hollow%20hold.png`,
  
  // Segunda parte - Mapeamento de imagens
  "Jump lunge": `${SUPABASE_PUBLIC_URL}/images/Jump%20lunge.png`,
  "Jump squat": `${SUPABASE_PUBLIC_URL}/images/Jump%20squat.png`,
  "Jumping jacks": `${SUPABASE_PUBLIC_URL}/images/Jumping%20jacks.png`,
  "Leg press 45°": `${SUPABASE_PUBLIC_URL}/images/Leg_press_45.png`,
  "L-sit": `${SUPABASE_PUBLIC_URL}/images/L-sit.png`,
  "Marcha estacionária": `${SUPABASE_PUBLIC_URL}/images/Marcha_estacionaria.png`,
  "Mergulho em barras": `${SUPABASE_PUBLIC_URL}/images/Mergulho%20em%20barras.png`,
  "Mobilidade articular": `${SUPABASE_PUBLIC_URL}/images/Mobilidade%20articular.png`,
  "Muscle-up": `${SUPABASE_PUBLIC_URL}/images/Muscle-up.png`,
  "Panturrilha em pé": `${SUPABASE_PUBLIC_URL}/images/Panturrilha_em_pe.png`,
  "Pike push-up (flexão elevada)": `${SUPABASE_PUBLIC_URL}/images/Pike_push_up.png`,
  "Pistol squat": `${SUPABASE_PUBLIC_URL}/images/Pistol%20squat.png`,
  "Pistol squat assistido": `${SUPABASE_PUBLIC_URL}/images/Pistol%20squat%20assistido.png`,
  "Prancha": `${SUPABASE_PUBLIC_URL}/images/Prancha.png`,
  "Prancha com drag": `${SUPABASE_PUBLIC_URL}/images/Prancha%20com%20drag.png`,
  "Prancha com shoulder tap": `${SUPABASE_PUBLIC_URL}/images/Prancha%20com%20shoulder%20tap.png`,
  "Prancha frontal": `${SUPABASE_PUBLIC_URL}/images/Prancha_frontal.png`,
  "Prancha lateral": `${SUPABASE_PUBLIC_URL}/images/Prancha%20lateral.png`,
  "Prancha no joelho": `${SUPABASE_PUBLIC_URL}/images/Prancha_no_joelho.png`,
  "Pseudo planche push-up": `${SUPABASE_PUBLIC_URL}/images/Pseudo%20planche%20push-up.png`,
  "Pull-up": `${SUPABASE_PUBLIC_URL}/images/Pull-up.png`,
  "Pull-up (barra fixa)": `${SUPABASE_PUBLIC_URL}/images/Pull-up_barra_fixa.png`,
  "Pull-up negativa": `${SUPABASE_PUBLIC_URL}/images/Pull-up%20negativa.png`,
  "Push-up plus": `${SUPABASE_PUBLIC_URL}/images/Push-up%20plus.png`,
  "Puxada aberta": `${SUPABASE_PUBLIC_URL}/images/Puxada_aberta.png`,
  "Puxada alta": `${SUPABASE_PUBLIC_URL}/images/Puxada_alta.png`,
  "Puxada frontal": `${SUPABASE_PUBLIC_URL}/images/Puxada_frontal.png`,
  "Remada baixa": `${SUPABASE_PUBLIC_URL}/images/Remada_baixa.png`,
  "Remada cavalinho": `${SUPABASE_PUBLIC_URL}/images/Remada_cavalinho.png`,
  "Remada curvada": `${SUPABASE_PUBLIC_URL}/images/Remada_curvada.png`,
  "Remada invertida": `${SUPABASE_PUBLIC_URL}/images/Remada%20invertida.png`,
  "Remada sentada": `${SUPABASE_PUBLIC_URL}/images/Remada_sentada.png`,
  "Remada unilateral com haltere": `${SUPABASE_PUBLIC_URL}/images/Remada_unilateral_com_haltere.png`,
  "Rosca alternada com halteres": `${SUPABASE_PUBLIC_URL}/images/Rosca_alternada_com_halteres.png`,
  "Rosca direta": `${SUPABASE_PUBLIC_URL}/images/Rosca%20direta.png`,
  "Rosca direta com barra": `${SUPABASE_PUBLIC_URL}/images/Rosca_direta_com_barra.png`,
  "Rosca scott": `${SUPABASE_PUBLIC_URL}/images/Rosca_scott.png`,
  "Rotação de tronco": `${SUPABASE_PUBLIC_URL}/images/Rotacao_de_tronco.png`,
  "Russian twist": `${SUPABASE_PUBLIC_URL}/images/Russian_twist.png`,
  "Salto em caixa ou banco": `${SUPABASE_PUBLIC_URL}/images/Salto%20em%20caixa%20ou%20banco.png`,
  "Sprint e caminhada": `${SUPABASE_PUBLIC_URL}/images/Sprint%20e%20caminhada.png`,
  "Sprints": `${SUPABASE_PUBLIC_URL}/images/Sprints.png`,
  "Stiff": `${SUPABASE_PUBLIC_URL}/images/Stiff.png`,
  "Superman": `${SUPABASE_PUBLIC_URL}/images/Superman.png`,
  "Supino inclinado com halteres": `${SUPABASE_PUBLIC_URL}/images/Supino_inclinado_com_halteres.png`,
  "Supino máquina": `${SUPABASE_PUBLIC_URL}/images/Supino_maquina.png`,
  "Supino reto": `${SUPABASE_PUBLIC_URL}/images/Supino%20reto.png`,
  "Supino reto com barra": `${SUPABASE_PUBLIC_URL}/images/Supino_reto_com_barra.png`,
  "Supino sentado": `${SUPABASE_PUBLIC_URL}/images/Supino_sentado.png`,
  "Treino em circuito": `${SUPABASE_PUBLIC_URL}/images/Treino%20em%20circuito.png`,
  "Treino intervalado": `${SUPABASE_PUBLIC_URL}/images/Treino%20intervalado.png`,
  "Tríceps corda": `${SUPABASE_PUBLIC_URL}/images/Triceps_corda.png`,
  "Tríceps francês": `${SUPABASE_PUBLIC_URL}/images/Triceps_frances.png`,
};

// Mapeamento de nomes de exercícios para URLs de vídeos
export const exerciseVideoMap: Record<string, string> = {
  "Abdominal bicicleta": "https://vimeo.com/570418723",
  "Abdominal completo": "https://vimeo.com/458656744",
  "Abdominal curto": "https://vimeo.com/562033518",
  "Abdominal infra": "https://vimeo.com/559136942",
  "Abdução de quadril": "https://vimeo.com/1007396947",
  "Afundo": "https://vimeo.com/591087584",
  "Afundo andando": "https://vimeo.com/591087584",
  "Afundo búlgaro": "https://vimeo.com/716855850",
  "Afundo com salto": "https://vimeo.com/1070471830",
  "Afundo estático": "https://vimeo.com/1077938106",
  "Agachamento búlgaro": "https://vimeo.com/471440654",
  "Agachamento com salto": "https://vimeo.com/482899311",
  "Agachamento livre": "https://vimeo.com/560469740",
  "Agachamento na parede": "https://vimeo.com/458732080",
  "Agachamento Smith": "https://vimeo.com/1074491796",
  "Agachamento sumô": "https://vimeo.com/569024196",
  "Alongamento de isquiotibiais": "https://vimeo.com/576475475",
  "Alongamento de ombros": "https://vimeo.com/585565189",
  "Alongamento dinâmico": "https://vimeo.com/463450280",
  "Aquecimento dinâmico": "https://vimeo.com/358550035",
  "Australian pull-up": "https://vimeo.com/539951634",
  "Bicicleta ergométrica": "https://vimeo.com/1049763887",
  "Burpee": "https://vimeo.com/560258550",
  "Cadeira extensora": "https://vimeo.com/245040059",
  "Cadeira flexora": "https://vimeo.com/245040184",
  "Crucifixo": "https://vimeo.com/716857575",
  "Crucifixo máquina": "https://vimeo.com/494208405",
  "Crucifixo na máquina": "https://vimeo.com/563388808",
  "Crunch abdominal": "https://vimeo.com/458656869",
  "Desenvolvimento com halteres": "https://vimeo.com/716846478",
  "Desenvolvimento máquina": "https://vimeo.com/1037196793",
  "Dips em cadeira": "https://www.youtube.com/watch?v=HCf97NPYeGY",
  "Dragon flag": "https://vimeo.com/602438981",
  "Elevação de calcanhar": "https://vimeo.com/439121024",
  "Elevação de panturrilha": "https://vimeo.com/1051293037",
  "Elevação de pernas": "https://vimeo.com/262269915",
  "Elevação frontal": "https://vimeo.com/245013621",
  "Elevação lateral": "https://vimeo.com/245016384",
  "Elevação lateral de braços": "https://vimeo.com/563390751",
  "Elevação pélvica": "https://vimeo.com/716853044",
  "Escalador": "https://vimeo.com/377381159",
  "Flexão archer": "https://vimeo.com/1049842087",
  "Flexão com apoio elevado": "https://vimeo.com/249714023",
  "Flexão com palma": "https://www.youtube.com/watch?v=aEk3DDFnDuw",
  "Flexão de braço": "https://vimeo.com/467746018",
  "Flexão de braço no banco": "https://www.youtube.com/watch?v=lZC8ak-axMM",
  "Flexão de braço no joelho": "https://vimeo.com/554854721",
  "Flexão declinada": "https://vimeo.com/1049842045",
  "Flexão hindu": "https://vimeo.com/1049852404",
  "Flexão na parede": "https://vimeo.com/569185083",
  "Flexões diamante": "https://vimeo.com/560258760",
  "Handstand push-up na parede": "https://www.youtube.com/watch?v=XckEEwa1BPI",
  "Hollow hold": "https://vimeo.com/509676778",
  
  // Segunda parte - Mapeamento de vídeos
  "Jump lunge": "https://vimeo.com/632075887",
  "Jump squat": "https://vimeo.com/632054119",
  "Jumping jacks": "https://vimeo.com/632072662",
  "Leg press 45°": "https://vimeo.com/245040473",
  "L-sit": "https://vimeo.com/280927636",
  "Marcha estacionária": "https://vimeo.com/358358998",
  "Mergulho em barras": "https://vimeo.com/526713591",
  "Muscle-up": "https://vimeo.com/378341589",
  "Panturrilha em pé": "https://vimeo.com/930015504",
  "Pistol squat": "https://vimeo.com/632076113",
  "Pistol squat assistido": "https://www.youtube.com/shorts/q5sbqedk5tc",
  "Ponte de glúteos": "https://vimeo.com/1083372695",
  "Ponte de glúteos com elevação de perna": "https://vimeo.com/1012863371",
  "Prancha": "https://vimeo.com/632100404",
  "Prancha com drag": "https://www.youtube.com/watch?v=h9zFpnekbno",
  "Prancha com elevação": "https://vimeo.com/1051272566",
  "Prancha com rotação": "https://vimeo.com/230172936",
  "Prancha com shoulder tap": "https://www.youtube.com/watch?v=GhmPoVjTVxE",
  "Prancha frontal": "https://vimeo.com/552009193",
  "Prancha lateral": "https://vimeo.com/632099916",
  "Prancha no joelho": "https://vimeo.com/632095004",
  "Pseudo planche push-up": "https://vimeo.com/498733989",
  "Pull-up": "https://vimeo.com/377617573",
  "Pull-up (barra fixa)": "https://vimeo.com/377617573",
  "Pull-up negativa": "https://www.youtube.com/watch?v=EkpJkHpJXmM",
  "Push-up plus": "https://vimeo.com/52085187",
  "Puxada aberta": "https://vimeo.com/245029417",
  "Puxada alta": "https://vimeo.com/564002269",
  "Puxada frontal": "https://vimeo.com/564002244",
  "Remada baixa": "https://vimeo.com/246101857",
  "Remada cavalinho": "https://vimeo.com/1078524727",
  "Remada curvada": "https://vimeo.com/568614325",
  "Remada em pé com elástico": "https://www.youtube.com/watch?v=voynCSavKak",
  "Remada invertida": "https://vimeo.com/1049014738",
  "Remada sentada": "https://vimeo.com/1049008940",
  "Remada unilateral com haltere": "https://vimeo.com/716848538",
  "Rosca alternada com halteres": "https://vimeo.com/568553892",
  "Rosca direta": "https://vimeo.com/716857833",
  "Rosca direta com barra": "https://vimeo.com/568614676",
  "Rosca scott": "https://vimeo.com/490845185",
  "Rotação de tronco": "https://vimeo.com/463450105",
  "Russian twist": "https://vimeo.com/568553051",
  "Salto em caixa ou banco": "https://www.youtube.com/watch?v=5gORKX-qPEI",
  "Stiff": "https://vimeo.com/568613698",
  "Superman": "https://vimeo.com/482900765",
  "Supino inclinado com halteres": "https://vimeo.com/568553375",
  "Supino máquina": "https://vimeo.com/564013235",
  "Supino reto": "https://vimeo.com/552015637",
  "Supino reto com barra": "https://vimeo.com/245918308",
  "Supino sentado": "https://vimeo.com/915604101",
  "Tríceps corda": "https://vimeo.com/564013337",
  "Tríceps francês": "https://vimeo.com/568552938",
  "Tríceps mergulho": "https://vimeo.com/1050864289",
  "Tríceps no banco": "https://vimeo.com/569185444"
};

/**
 * Função para obter a URL da imagem de um exercício
 * @param exerciseName Nome do exercício
 * @returns URL da imagem específica ou URL de fallback
 */
export const getExerciseImageUrl = (exerciseName: string): string => {
  // Verifica se existe uma imagem específica para o exercício
  if (exerciseImageMap[exerciseName]) {
    return exerciseImageMap[exerciseName];
  }
  
  // Fallback para URL genérica baseada no nome do exercício
  return `https://source.unsplash.com/random/400x300/?${encodeURIComponent(exerciseName.replace(' ', '-'))}&fitness`;
};

/**
 * Função para obter a URL do vídeo de um exercício
 * @param exerciseName Nome do exercício
 * @returns URL do vídeo ou null se não existir
 */
export const getExerciseVideoUrl = (exerciseName: string): string | null => {
  return exerciseVideoMap[exerciseName] || null;
};
