// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqtihdzdyqygsspvsfyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxdGloZHpkeXF5Z3NzcHZzZnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTQxOTQsImV4cCI6MjA2MzMzMDE5NH0.QY7-6zNrzxr-QiYgjAT5gcbbyH5OEYqOJkbiWPd5ixA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);